### ISSUE TITLE
UAV running out of battery

### ISSUE THREAD

**Issue by micha-sommer** [ThomDietrich/multiUAV-simulation#32]
I think we must overthing the exchange to not charge the node too late:
![image](https://user-images.githubusercontent.com/638368/37092181-158ffd46-220b-11e8-8c50-80a19b23df86.png)
Can be reconstructed with b60ea107bea2a23751b4c23f30b7e16a8cb5de67 and inifile configuration *mission-Nr-01*.

**Comment by ThomDietrich** [comment]
Seeing the same behavior.
However it seems like the problem is not related to the consumption calculation. I'm not sure why but uav[0] continues to the Sporthalle after the EX command, which shouldn't happen. Any idea why that is?

**Comment by ThomDietrich** [comment]
**Off-Topic**

Hallo @somi0815 und @LudwigBr,

ich bin mal so frei und missbrauche dieses Ticket um euch eine Nachricht zukommen zu lassen. 😄 Ihr hattet beide darum gebeten, ich habe bisher mein Versprechen aber nicht eingehalten. Ich habe meine Dissertation im September letzten Jahres abgegeben und im Juli hatte ich dann die Verteidigung. Alles lief problemlos.
Ich möchte euch noch einmal danken. Euer Engagement hier im Repo war super und unsere Diskussionen über das weitere Vorgehen unschätzbar für meinen Fortschritt. Die Arbeit wäre in Ihrer aktuellen Form ohne eure Hilfe nicht möglich gewesen. Danke!
Wie geht es euch mittlerweile? Wo hat es euch hinverschlagen? Ich würde mich über eine Antwort freuen, entweder hier oder als kurze Mail an thomas@nurzen.de

Viele Grüße! Thomas
